#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMining
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class DMDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DMDBDataContext() : 
				base(global::DataMining.Properties.Settings.Default.DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DMDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DMDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Golf> Golfs
		{
			get
			{
				return this.GetTable<Golf>();
			}
		}
	}
	
	[Table(Name="dbo.Golf")]
	public partial class Golf
	{
		
		private string _Observation;
		
		private string _Temperature;
		
		private string _Humidity;
		
		private string _Wind;
		
		private string _Game;
		
		public Golf()
		{
		}
		
		[Column(Storage="_Observation", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Observation
		{
			get
			{
				return this._Observation;
			}
			set
			{
				if ((this._Observation != value))
				{
					this._Observation = value;
				}
			}
		}
		
		[Column(Storage="_Temperature", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Temperature
		{
			get
			{
				return this._Temperature;
			}
			set
			{
				if ((this._Temperature != value))
				{
					this._Temperature = value;
				}
			}
		}
		
		[Column(Storage="_Humidity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Humidity
		{
			get
			{
				return this._Humidity;
			}
			set
			{
				if ((this._Humidity != value))
				{
					this._Humidity = value;
				}
			}
		}
		
		[Column(Storage="_Wind", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Wind
		{
			get
			{
				return this._Wind;
			}
			set
			{
				if ((this._Wind != value))
				{
					this._Wind = value;
				}
			}
		}
		
		[Column(Storage="_Game", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Game
		{
			get
			{
				return this._Game;
			}
			set
			{
				if ((this._Game != value))
				{
					this._Game = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
